name: project_base
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.2.5 <4.0.0"

# Add regular dependencies here.
dependencies:
  alfred:
  crypto:
  dart_jsonwebtoken:
  dotenv:
  fixnum:
  json_annotation:
  mailer:
  mime:
  mongo_dart:
  # path: ^1.8.0
  very_good_analysis: any

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  lints: ^6.0.0
  test: ^1.24.0
